### ISSUE TITLE
Doesn't work on Windows.

### ISSUE THREAD

**Issue by lvendrame** [rage8885/OpenSC2K#14]
I saw this error on Electron Developer Tools
`Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\OpenSC2K\node_modules\better-sqlite3\build\Release\better_sqlite3.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (D:\OpenSC2K\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (D:\OpenSC2K\node_modules\better-sqlite3\lib\database.js:4:40)`

**Comment by cdubz** [comment]
Check out #4, looks like the same issue with better-sqlite3.

**Comment by lvendrame** [comment]
Tks
