### ISSUE TITLE
Couldn't set selectedTextBackgroundColor from default ()

### ISSUE THREAD

**Issue by phocks** [rage8885/OpenSC2K#16]
Cloned, npm install, npm start

On macOS High Sierra

I get: `2018-02-07 13:18:13.574 Electron Helper[70006:6619075] Couldn't set selectedTextBackgroundColor from default ()`

and in the Electron console. 

```
Error: The module '/Users/byrdj5d/Sites/OpenSC2K/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/Users/byrdj5d/Sites/OpenSC2K/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/Users/byrdj5d/Sites/OpenSC2K/node_modules/better-sqlite3/lib/database.js:4:40)
```

And I just get a blank brown screen

**Comment by whphhg** [comment]
Try `node_modules/.bin/electron-rebuild -f -w better-sqlite3`. It worked for Windows in #4 and Linux in #5.

**Comment by phocks** [comment]
Yes this fixed it. Thanks!
