### ISSUE TITLE
The module '../better_sqlite3.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 59. This version of Node.js requires NODE_MODULE_VERSION 57.

### ISSUE THREAD

**Issue by tsiq-swyx** [rage8885/OpenSC2K#31]
getting this in the electron window when i run :(

```
Uncaught Error: The module '/Users/swyx/OpenSource/OpenSC2K/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)

```
![image](https://user-images.githubusercontent.com/35976578/36051416-0c6731a6-0db8-11e8-86c6-1067173cf389.png)

steps i have tried to do:

- this to fix my xcode warnings when i `npm install better-sqlite3`: <https://github.com/nodejs/node-gyp/issues/569>
- this aka `npm rebuild`: https://github.com/rage8885/OpenSC2K/issues/5

i am on a new mac with the latest whatevers. Any other ideas on what I can tryplease? thank you very much.

**Comment by cursorial** [comment]
Did you follow the README instructions? Can you remove the directory, clone again, try the steps and post a pastebin of your output?
