### ISSUE TITLE
Fails to start on Linux due to better-sqlite3 compiled version mismatch

### ISSUE THREAD

**Issue by whphhg** [rage8885/OpenSC2K#5]
First of all, thank you for creating and open sourcing this! I used to love the original game, so this will be an awesome way to play from time to time and see the inner workings as well. :1st_place_medal: 

After `npm install` I removed the comment enabling `mainWindow.webContents.openDevTools()` in `main.js` and the issue is (I've tried `npm rebuild` like it suggested as well):
```
Uncaught Error: The module '/home/user/OS/OpenSC2K/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/home/user/OS/OpenSC2K/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/user/OS/OpenSC2K/node_modules/better-sqlite3/lib/database.js:4:40)
```

```
node v9.5.0
npm v5.6.0
```

**Comment by cursorial** [comment]
Did you try rebuilding/reinstalling the module?

**Comment by whphhg** [comment]
Not the module itself. How do I do that?

**Comment by cursorial** [comment]
npm rebuild better-sqlite3

or 

   npm install better-sqlite3

**Comment by whphhg** [comment]
I've tried the following combinations but no cigar:
- `npm rebuild better-sqlite3` after a clean install
- installing `better-sqlite3` and starting
- rebuilding the project and the module after installing `better-sqlite3`

**Comment by cdubz** [comment]
See #4 as well - have you tried rebuilding electron with that command?

**Comment by whphhg** [comment]
Rebuilding right now (just read your issue)! Will let you know in a bit.
